### ISSUE TITLE
[Discussion] Using TSem or TChan as the throttle

### ISSUE THREAD

**Issue by athanclark** [creichert/wai-middleware-throttle#10]
Hey there,

I just looked through your code a bit, because this project sounds really interesting. But anyway, I argue that using `TSem` or `TChan` as the fundamental throttling mechanism would be a cleaner design than expecting the user to _manually_ retry. Instead of thinking about delays, you think more about the "size" of the semaphore.

You can treat the semaphore / channel itself as a resource, where allocation is done before your value is evaluated, and deallocation is _always_ performed, even in the presence of an error. That makes it a perfect case for `bracket_`:

```haskell
bracket_ allocate deallocate performRestOfMiddleware
  where
    allocate :: IO ()
    allocate = waitTSem throttleTSem

    deallocate :: IO ()
    deallocate = signalTSem throttleTSem
```

Of course a redesign like this would require some scrubbing, but I think it would make it a lot more valuable. What do you think?

**Comment by athanclark** [comment]
I think this would work:

```haskell
throttleMiddleware :: Int -> IO Middleware
throttleMiddleware n = do
  sem <- newTSem n
  pure $ \app req resp -> bracket_ (waitTSem sem) (signalTSem sem) (app req resp)
```

**Comment by creichert** [comment]
@athanclark cool! thanks for the discussion points. I haven't had a ton of time to look into this but I want to make sure I'm on the same page:

> a cleaner design than expecting the user to manually retry.

You mean the user making the HTTP request to the server, right? (not the user of some library).

One goal I had when originally building this middleware was for it to behave similarly to Nginx's `limit_req`. The throttle failure uses a distinct HTTP status code in Nginx and does in this middleware. Thinking further, maybe it would have been more appropriate to call it "wai-middleware-rate-limit" as opposed to "wai-middleware-throttle"

So, if I understand correctly, your proposing actually holding a request for some time as opposed to responding immediately w/ a status code error. Am I understanding correctly?

**Comment by athanclark** [comment]
Oh! No I was mistaken, I didn't recognize the purpose. Sorry for the late reply!
