### ISSUE TITLE
Release v2.2

### ISSUE THREAD

**Issue by dfithian** [creichert/wai-middleware-throttle#12]
This has been a FIXME in my `stack.yaml`s for a while now... I'm happy to release this, but I don't have the permissions on Hackage (and I haven't actually released something before so I'm unsure how to do it).

**Comment by creichert** [comment]
I'm looking into this but ran into a few problems building the package w/ the latest nightly:

> Unable to parse cabal file: FromString "This package requires at least Cabal version 2.0" Nothing

What snapshot version are you trying to use this with?

I'll keep trying to fix it, but if  you have time to attempt to build it against the latest nightly, that would help. Thanks!

**Comment by dfithian** [comment]
I'm happy to do it tomorrow, or if I don't get to it will do so Saturday morning!

**Comment by dfithian** [comment]
I'm using this with 9.13, which is the latest, and it's compiling as an extra-dep (building from source) in my stack.yaml

**Comment by creichert** [comment]
With 9.13, it's building successfully for me. However, I get the error I posted when I use the latest nightly. Were you able to build successfully with that? If so, we can enable it in the stackage build-constraints.yaml.

> Unable to parse cabal file: FromString "This package requires at least Cabal version 2.0" Nothing

**Comment by dfithian** [comment]
I was able to build successfully with both 9.13 and nightly. I am building on macOS High Sierra with Stack version 1.5.1.

I found [this](https://stackoverflow.com/questions/45815830/cabal-2-0-required-when-using-a-nightly-snapshot-with-stack) article that mentions you probably need to use 1.5.1; are you on that version?

**Comment by creichert** [comment]
Tagged: https://github.com/creichert/wai-middleware-throttle/releases
Uploaded version: https://hackage.haskell.org/package/wai-middleware-throttle

Can you double-check my work? Also, I can add you as a Hackage maintainer if you shoot me your username.


---

One issue is the `./scripts` directory which raises several package exceptions. I'm not exactly sure what to do with that package, but it might be a good idea to use the stack `script` interpreter:

```
Getting file list for /home/christopher/dev/haskell/wai-middleware-throttle/script/
Building sdist tarball for /home/christopher/dev/haskell/wai-middleware-throttle/script/
Warning: These files are outside of the package directory, and will be omitted from the tarball: ["../LICENSE"]
Checking package 'script' for common mistakes
Package check reported the following warnings:
No 'category' field.
'ghc-options: -Wall -Werror' makes the package very easy to break with future GHC versions because new GHC versions often add new warnings. Use just 'ghc-options: -Wall' instead.
'ghc-options: -O2' is rarely needed. Check that it is giving a real benefit and not just imposing longer compile times on your users.
The 'license-file' field refers to the file '../LICENSE' which does not exist.
Package check reported the following errors:
No 'synopsis' or 'description' field.
The dependency 'build-depends: base' does not specify an upper bound on the version number. Each major release of the 'base' package changes the API in various ways and most packages will need some changes to compile with it. The recommended practise is to specify an upper bound on the version of the 'base' package. This ensures your package will continue to build when a new major version of the 'base' package is released. If you are not sure what upper bound to use then use the next  major version. For example if you have tested your package with 'base' version 2 and 3 then use 'build-depends: base >= 2 && < 4'.
The package is missing a Setup.hs or Setup.lhs script.
```

**Comment by creichert** [comment]
Also, the existence of the `./scripts` directory in the main stack.yaml incurs a large number of dependencies that the package wouldn't otherwise need since most users likely won't be running the benchmarks.

We could use a script interpreter and build/run it during CI. Let me know what you think.

**Comment by dfithian** [comment]
Oh yes, I agree, shouldn't be distributed. Running it as part of CI is definitely a good idea, though it's obviously more diagnostic than a "test case". Quick fix for removing this is just to remove it from the `packages` stanza in stack.yaml?

The tag looks good.

When I go to the [hackage](https://hackage.haskell.org/package/wai-middleware-throttle) page, I see "Distributions" as having the old version (0.2.1.0). I also can't click on docs for Network.Wai.Middleware.Throttle - do they need to be uploaded as well somehow?

**Comment by dfithian** [comment]
Oh and my hackage username is `dfithian`

**Comment by creichert** [comment]
- I added you as a Hackage maintainer

- The documentation builds can take a bit but they will popup

- I just created a PR on stackage https://github.com/fpco/stackage/pull/3036
