### ISSUE TITLE
Improvements based on reddit thread (feedback)

### ISSUE THREAD

**Issue by creichert** [creichert/wai-middleware-throttle#16]
- https://www.reddit.com/r/haskell/comments/7e2g29/warp_how_to_limit_requests_per_second_to_each/

Most notably:

> Please keep in mind that this middleware needs a bit of work before it can safely be used on high traffic production sites: The representation of the retry state is quite inefficient and due to the read and write in the STM var being split in two transaction you will loose writes. Also the internal state is never cleaned up.

**Comment by dfithian** [comment]
It could be a good time to take this on... so far my company has used this on a small scale but we're beginning to see performance problems specifically with respect to memory and CPU leaks that could be influenced by this.

**Comment by creichert** [comment]
Lots of fixes in #18 address this, including some benchmarks and heap reports. I'm closing this for now. We will address further issues on a case by case basis. 

Good work @dfithian
